FROM php:5.6.31-apache

MAINTAINER Marius Millea <mariusmillea@gmail.com>

# install packages 
RUN echo 'deb http://ftp.debian.org/debian jessie-backports main' >> /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        cron \
        inotify-tools \
        libjpeg62-turbo-dev \
        libpng12-dev \
        mysql-client \
        nano \
        python \
        rsyslog \
        supervisor \
        vim-tiny \
        wget \
    && apt-get install -y -t jessie-backports openssl \
    && wget https://git.io/psysh -O /usr/bin/psysh \
    && chmod +x /usr/bin/psysh \
    && rm -rf /var/lib/apt/lists

# configure server
RUN docker-php-ext-install mysqli \
    && docker-php-ext-configure gd --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && a2enmod cgi
    
#install Docker client
RUN curl -L http://get.docker.com/builds/Linux/x86_64/docker-1.10.3 > /usr/bin/docker \
    && chmod +x /usr/bin/docker

# build args from the docker-compose.yml / .env files
ARG BOINC_USER
ARG PROJECT_ROOT
ENV USER=$BOINC_USER BOINC_USER=$BOINC_USER HOME=/home/$BOINC_USER PROJECT_ROOT=$PROJECT_ROOT

# set up the non-root user who runs the dameons
RUN adduser $BOINC_USER --disabled-password --gecos ""

# so that www-data can read/write boinc server files
RUN adduser www-data $BOINC_USER

# a prettier shell
COPY --chown=1000:1000 .bashrc $HOME/.bashrc

# logrotate
COPY --chown=1000:1000 logrotate /etc/logrotate.d/boincserver
RUN chmod 644 /etc/logrotate.d/boincserver

# ensure the project volume has the right permissions when mounted
RUN mkdir $PROJECT_ROOT && chown $BOINC_USER:$BOINC_USER $PROJECT_ROOT
    
# set up supervisor to run
COPY makeproject-step3.sh /usr/bin/
COPY supervisord.conf /etc/supervisor/conf.d/
CMD ["/usr/bin/supervisord"]
